import { GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import {useRouter} from "next/router";
import { signIn } from "next-auth/react";
import { getServerAuthSession } from "~/server/auth";

const Home: NextPage = () => {
    const router = useRouter()

    return (
        <>
            <Head>
                <title>What?</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex items-center justify-center min-h-screen bg-deepPurple text-superCoolEdgyPurple ">
                <div className="flex h-screen text-center">

                    <div className="m-auto">
                    <h1 className="font-bold text-3xl my-5">Sign in with an Auth Provider:</h1>
                        <div className="flex flex-col space-y-2">
                            <button className={"bg-puddlePurple p-2 text-xl"} onClick={() => void signIn("discord")}>Discord</button>
                        </div>

                        <div className={"my-5"}>
                            <button onClick={() => void router.push("FAQ")}>FAQ</button>
                        </div>
                    </div>
                </div>

            </main>

        </>
    )
};

export async function getServerSideProps(ctx:GetServerSidePropsContext) {
    const session = await getServerAuthSession(ctx)

    if(session){
        return {
            redirect: {
                destination: "/groupSelect",
                permanent: false
            }
        };
    }


    return {
        props: { session },
    }
}

export default Home;
