import { GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { signIn } from "next-auth/react";
import { getServerAuthSession } from "~/server/auth";

const Home: NextPage = () => {
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Text Uploader</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex items-center justify-center min-h-screen bg-deepPurple text-superCoolEdgyPurple ">
                <div className="flex h-screen text-center">

                    <div className="m-auto">
                        <h1 className="font-bold text-4xl my-5">ShareX Text Uploader</h1>

                        <h1 className="font-bold text-2xl my-5">Please sign in with an Auth Provider:</h1>

                        <div className="flex flex-col space-y-2">
                            <button className={"bg-puddlePurple p-2 text-xl"}
                                    onClick={() => void signIn("discord")}>Discord
                            </button>
                            <button className={"bg-puddlePurple p-2 text-xl"}
                                    onClick={() => void signIn("github")}>GitHub
                            </button>
                            <button className={"bg-puddlePurple p-2 text-xl"}
                                    onClick={() => void signIn("google")}>Google
                            </button>
                        </div>

                        <div className={"flex flex-col"}>
                            <h1 className="font-bold text-2xl my-5">Or Submit a paste without an account:</h1>
                            <button className={"bg-puddlePurple p-2 text-xl"}
                                    onClick={() => void router.push("/anonSubmit")}>Submit
                            </button>
                        </div>



                        <div className={"my-10 text-xl bg-puddlePurple cursor-pointer"} onClick={() => void router.push("FAQ")} >
                            FAQ
                        </div>
                    </div>
                </div>

            </main>

        </>
    );
};

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
    const session = await getServerAuthSession(ctx);

    if (session) {
        return {
            redirect: {
                destination: "/groupSelect",
                permanent: false
            }
        };
    }


    return {
        props: { session }
    };
}

export default Home;
