import type {FC} from "react"
import Head from "next/head";
import stare from "../misc/stare.png"
import Image from "next/image"

const Stop: FC = ({}) => {
    return (
        <>
            <Head>
                <title>Text Uploader</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex items-center justify-center min-h-screen bg-deepPurple text-superCoolEdgyPurple ">

                <div className="flex h-screen text-center">
                    <div className="m-auto">
                        <h1 className="font-bold text-3xl my-5  ">Stop</h1>
                        <Image alt={"stop."} src={stare} />

                    </div>
                </div>
            </main>
        </>
    )
}

export default Stop